### ISSUE TITLE
Feature Request: Add commandline parameter for "Transparent" setting in "General/Colors" section

### ISSUE THREAD

**Issue by tvhdev** [tcobbs/ldview#11]
Hi there, i misunderstood the setting -SaveAlpha (alpha channel of a png file), sorry for that. I thought it had s.th. to do with the "General/Colors" Section checkbox "Transparent". 

So my feature request would be to have a command line parameter implemented for the "Transparent" checkbox under "General/Colors", similar to "DefaultColor3" and "BackgroundColor3".

What do you think?

Thanks for your great work and sorry again for my confusion.

**Comment by tcobbs** [comment]
I responded to your other issue, but I'll respond here too. There is already a command line option to do this: -TransDefaultColor=1. I will fix Help.html to properly document that option, as it currently says it is equivalent to the _Trans_ check, when it should say _Transparent_ check.

**Comment by tvhdev** [comment]
Oh,cool,thank you for the fast response. I will try that setting then. Thanks for your great work and for updating the documentation.
