### ISSUE TITLE
Sourceforge site give no indication that more recent releases are available here

### ISSUE THREAD

**Issue by jpuderer** [tcobbs/ldview#12]
This is more of a "meta" project issue.

It's not well advertised that LDView development and releases have moved here from SourceForge.  I almost didn't know that more recent versions exists, except by a bit of random searching I did mostly after the fact.

The ldraw.org website also points at the older SourceForge site: https://wiki.ldraw.org/wiki/LDView (I tried to update it myself, but the change was rejected).  I sent a follow up email to the webmaster of ldraw.org, but I can't do anything about SourceForge.

Love the project!  Amazing work.  Wouldn't want others to miss out.

**Comment by MinnieTheMoocher** [comment]
I checked  https://wiki.ldraw.org/wiki/LDView and could not find the problem you reported:
that site correctly points to GitHub, not SourceForge

**Comment by pniederlag** [comment]
https://wiki.ldraw.org/wiki/Getting_Started_-_Linux points to sourceforge. I ran into the very same issue until I googled "ldraw github". If someone has an account over there it would be nice to redirect that to here.

**Comment by tcobbs** [comment]
This should now be fixed (although you might have to reload the SourceForge page). It should immediately redirect from SourceForge to GitHub, and there is a note at the top of each page indicating that the project moved to GitHub (with a link). For the "Getting Started - Linux" in particular on the Wiki, the #Linux hash does not make it through the redirect, so it ends up at the top of the page, but at least it is on GitHub. I updated all the relevant pages on SourceForge (omitting the generated m6459.html example file), so any deep links should be redirected.
