### ISSUE TITLE
Windows UI looks 'older' in 4.3 compared to 4.2

### ISSUE THREAD

**Issue by Landcross** [tcobbs/ldview#13]
I just updated LDView 4.2 to LDView 4.3 and I noticed that the Windows UI has changed.

For example take a look at this image in LDView 4.2 I took yesterday for an (unrelated) LPub3D issue:
![45512385-e2f21880-b79f-11e8-93ea-34806df4cf2e](https://user-images.githubusercontent.com/12005521/45535652-858db400-b7ff-11e8-8cd8-446506f011c6.png)

This is how it now looks in LDView 4.3:
![image](https://user-images.githubusercontent.com/12005521/45535672-950cfd00-b7ff-11e8-9f22-ff489a9e9e3d.png)

It looks more Windows XP'ish instead of Windows 7/10 ish. And it's not just there, the whole UI has gone backwards. Dialogs, toolbars, etc.

I'm using Windows 10 Pro 64 bit with LDView 4.3 64 bit.

**Comment by tcobbs** [comment]
LDView 4.4 should solve this problem when it is released. I _think_ that making 4.3 Windows XP-compatible in the toolset I was using is what caused the problem in the first place, but I'm not completely sure of that. LDView 4.4 will also support display scaling in Windows 10 1607 or Windows 10 1703. (I can't remember which it requires for the scaling to work right, but it doesn't work on original Windows 10 or Anniversary Update Windows 10; it requires something newer than that.)

**Comment by Landcross** [comment]
Nice to hear. While it doesn't impact usability if the software at all, it does look a bit strange especially since it looked better before. Is there any ETA for 4.4?

**Comment by tcobbs** [comment]
Unfortunately, there isn't an ETA for 4.4. There are some bugs that I seem to have introduced while developing it that I need to fix before it can be released.
