### ISSUE TITLE
Crash when using SaveSnapshot from Commandline

### ISSUE THREAD

**Issue by sbarzowski** [tcobbs/ldview#14]
When I try to use SaveSnapshot option the command crashes (Segmentation Fault). Interestingly problem appears only when using command line (I can export from GUI just fine).

Example command:
```
./LDView -v desin.ldr  -SaveSnapshot="design.png"
```

I tried running it under gdb and it seems that it crashes on this line: https://github.com/tcobbs/ldview/blob/master/LDLib/LDSnapshotTaker.cpp#L1521

Is it a known issue? Could it have something to do with this stuff https://github.com/tcobbs/ldview/commit/4f6209dfccbf2029436eedc225596f2f277435c4 ?

Version: current master (42bb3c5bb2)
OS: Arch Linux

**Comment by pbartfai** [comment]
Do you use Qt 4.x or 5.x?

**Comment by sbarzowski** [comment]
It's compiled with Qt5, to be precise Qt 5.12.2.

**Comment by trevorsandy** [comment]
The command console instance of LDView uses OSMesa. On Arch Linux there is an inconsistency with the prebuilt instance of OSMesa which causes LDView to fail when trying to create a context. My solution is to build OSMesa from source on Arch Linux. 

Here is my OSMesa build script: https://github.com/trevorsandy/lpub3d-ci/blob/master/builds/utilities/mesa/build_osmesa.sh 

Cheers,

**Comment by pbartfai** [comment]
Save snapshot feature was recently rewritten. Please test it again using Qt5.x.

**Comment by pbartfai** [comment]
@sbarzowski is the problem still presence with Qt5 version of LDView?

**Comment by pbartfai** [comment]
Tested latest ArchLinux running Qt5.x version of LDView and snapshot created properly from command line.
