### ISSUE TITLE
Feature request: set camera XYZ using user input

### ISSUE THREAD

**Issue by mjhorvath** [tcobbs/ldview#16]
The program already allows users to set the camera lat/long/radius positions. I think it would also be nice to be able to set the XYZ coordinates of the camera, as well as viewing angles and FOV. Thanks!!

**Comment by tcobbs** [comment]
@mjhorvath I have implemented this for macOS and Windows. (Linux forthcoming.) If you would like to try it out, send an email to the LDView email address, and I will send you a link to a build. Make sure to let me know which build(s) you want (Windows 32bit, Windows 64 bit, Mac, etc.).

**Comment by tcobbs** [comment]
This was added in version 4.4.
