### ISSUE TITLE
Invalid null pointer when snapshot suffix not specified

### ISSUE THREAD

**Issue by trevorsandy** [tcobbs/ldview#19]
In the latest codebase, when a snapshot suffix is not specified, e.g. when exporting a part list, an invalid null pointer exception is thrown.

![Screenshot - 08_10_2019 , 12_49_56](https://user-images.githubusercontent.com/13388970/66392950-92b0ae80-e9d1-11e9-860c-579d601bfbf0.png)

Invalid null pointer
![Screenshot - 08_10_2019 , 12_50_37](https://user-images.githubusercontent.com/13388970/66392972-9fcd9d80-e9d1-11e9-9af8-0387558267f7.png)

It seems like the `UCSTR snapshotSuffixTemp` pointer is not checked for null before assignment to `snapshotSuffix`.
![Screenshot - 08_10_2019 , 12_51_11](https://user-images.githubusercontent.com/13388970/66392986-a65c1500-e9d1-11e9-98e7-152eec28f4d4.png)

This update seems to correct the unexpected behaviour.
![Screenshot - 08_10_2019 , 13_47_04](https://user-images.githubusercontent.com/13388970/66393171-25514d80-e9d2-11e9-9c0d-629bb16d5cbb.png)

Cheers,

**Comment by tcobbs** [comment]
Thanks. I'll fix this (in a slightly different way).

--Travis

**Comment by tcobbs** [comment]
My commit is here:

https://github.com/tcobbs/ldview/commit/37889833c2cd8371deab2b23ee9bc98d2cd203fd

--Travis

**Comment by trevorsandy** [comment]
Excellent! Thank you.

Cheers,
