### ISSUE TITLE
IniFile load error message

### ISSUE THREAD

**Issue by trevorsandy** [tcobbs/ldview#2]
Hi Travis - I compiled an OSMesa-CUI for MacOSX. All seems well except I get [this ](https://github.com/tcobbs/ldview/blob/master/OSMesa/ldview.cpp#L75) error message (but successful result) because `if (!TCUserDefaults::isIniFileSet())` [link](https://github.com/tcobbs/ldview/blob/master/OSMesa/ldview.cpp#L59) returns false when, in fact, it should return true because my IniFile is specified on the command line.

After some debugging, I tracked down the fault to `virtual void addItem(Type newItem)` [link](https://github.com/tcobbs/ldview/blob/master/TCFoundation/TCArray.h#L40). This function is called by `int TCStringArray::addString(const char* newString)` [link](https://github.com/tcobbs/ldview/blob/master/TCFoundation/TCStringArray.cpp#L51) and I can verify the argv IniFile string is received by `addString(const char* newString)` and passed to `addItem(Type newItem)`; however, the string is never received by and, as a consequence, is not passed to `virtual void insertItem(Type newItem, unsigned int index = 0)` [link](https://github.com/tcobbs/ldview/blob/master/TCFoundation/TCArray.h#L45). While the IniFile string (or any strings in argv for that matter) is not received by `insertItem(Type newItem, unsigned int index = 0)`, The TCArray<void*>::argArray object's 'allocated' and 'count' attributes are properly updated. The 'items' attribute remains null however because there is not 'newItem' to insert.

As there is no string in items, `const char *iniFile = defCommandLineStringForKey("IniFile")` [link](https://github.com/tcobbs/ldview/blob/master/TCFoundation/TCUserDefaults.cpp#L1746) returns NULL so `setIniFile(iniFile)` [link](https://github.com/tcobbs/ldview/blob/master/TCFoundation/TCUserDefaults.cpp#L1749) is never executed.

As `addItem(Type newItem)` is of type virtual void, perhaps this behaviour may be related to the changes from back in 2008 in [Change TCArray to be templated, to allow TCTypedValueArray to be ported to 64 bit (which wasn't possible with the void*-based TCArray).](https://github.com/tcobbs/ldview/commit/e562d03de5dc44bc188b3bf3f577bfd35b01bb7d#diff-9320b36baeecf05774081a9b4b6425b5)

What do you think?

Cheers,

**Comment by tcobbs** [comment]
I can't reproduce this. When I add -IniFile=/Users/travis/LDView.ini to my command line for standard Mac LDView, it works. The debugger freaks out if I try to step into TCArray::insertItem from TCArray::addItem, but if I step over it, the item is inserted into the array as expected.

Can you tell me your exact command line?

**Comment by trevorsandy** [comment]
Here it is:
./LDView ../8464.mpd -SaveSnapshot=/tmp/8464.png IniFile=/Users/trevorsandy/Projects/ldview/OSMesa/LDViewCustomIni -SaveWidth=128 -SaveHeight=128 -ShowErrors=0 -SaveActualSize=0

...and the ini file contents:

[General]
; === LDView Global
AutoCrop=1
BackgroundColor3=00a2b6ce
ExamineMode=0
FullscreenDepth=20
FullscreenHeight=0
FullscreenWidth=0
IgnorePBuffer=0
JPGProgressive=0
JPGQuality=55
JPGSubSampling=2
LDrawDir=/Users/trevorsandy/Library/LDraw
SaveActualSize=1
SaveAlpha=1
SaveDigits=1
SaveImageType=1
SaveSeries=1
SaveSteps=0
; === PovExporter
Ambient=0.4
BottomInclude=
ChromeBril=5
ChromeRefl=0.85
ChromeRoughness=0.01
ChromeSpecular=0.8
ConditionalEdges=0
CustomAspectRatio=1.5
Diffuse=0.4
EdgeRadius=0.15
Edges=0
FileVersion=3.6
FindReplacements=0
Floor=0
FloorAxis=1
HideStuds=0
InlinePov=1
Phong=0.5
PhongSize=40
PrimitiveSubstitution=1
Quality=3
Refl=0.08
Reflections=1
RubberPhong=0.1
RubberPhongSize=10
RubberRefl=0
SeamWidth=0.5
SelectedAspectRatio=ffffffff
Shadows=1
SmoothCurves=1
TopInclude=
TransFilter=0.8
TransIoR=1.25
TransRefl=0.2
UnmirrorStuds=1
XmlMap=1
XmlMapPath=/Users/trevorsandy/Library/LDraw/lgeo

**Comment by tcobbs** [comment]
I mentioned it via email, but the IniFile=<blah> parameter needs to be -IniFile=<blah>.

**Comment by trevorsandy** [comment]
Oops! I must have been asleep at the wheel. Thanks!
