### ISSUE TITLE
Feature request: override minimum camera zoom

### ISSUE THREAD

**Issue by mjhorvath** [tcobbs/ldview#20]
Currently, there is a point where you can no longer zoom in the camera in Examine mode. Could you add an option somewhere to disable this so I can zoom all the way to the center? I have a very wide but short model which does not work well with the default behavior. Thanks.

**Comment by tcobbs** [comment]
This functionality has existed since 19 Feb, 2002, but does not (and will not ever) have a UI. See the ZoomMax setting in LDView's Help.html.

**Comment by mjhorvath** [comment]
I looked at the docs and I see now why you don't want to have a UI option. It is confusing.
