### ISSUE TITLE
TEXMAP and BFC INVERTNEXT do not work together

### ISSUE THREAD

**Issue by alex-taylor** [tcobbs/ldview#21]
```
0 BFC CERTIFY CCW

0 !TEXMAP START PLANAR -100 200 0  100 200 0  -100 0 0 sample.png
0 BFC INVERTNEXT
1 16 00 0 0 -100 0 0 0 200 0 0 0 -100 2-4cyli.dat
0 !TEXMAP END

```

The BFC INVERTNEXT statement in the above code isn't processed correctly:

 - with BFC disabled in LDView, the cylinder and texture render normally

![Image4](https://user-images.githubusercontent.com/5150717/83547292-e4c2b900-a4f9-11ea-89cc-10bc03eb1d88.png)

 - with BFC enabled and face highlighting disabled, the cylinder's front (inner) face renders in colour-16, but its back face is also rendered - with the texture applied to it

![Image5](https://user-images.githubusercontent.com/5150717/83547345-f86e1f80-a4f9-11ea-873a-7737514c6079.png)

 - with red back faces enabled, the *front* face of the cylinder is highlighted in red and the texture is applied to both faces

![Image6](https://user-images.githubusercontent.com/5150717/83547380-0885ff00-a4fa-11ea-8cdf-07ea0780d857.png)

 - with green front faces enabled, the *back* face of the cylinder is highlighted in green and the texture is applied to both faces

![Image7](https://user-images.githubusercontent.com/5150717/83547420-18054800-a4fa-11ea-9104-32e3c80a3186.png)

**Comment by tcobbs** [comment]
This is now fixed in the source tree.

**Comment by tcobbs** [comment]
@alex-taylor I created a 4.4 Alpha 6 release here on GitHub. You can test all my recent TEXMAP fixes in that release. Let me know if you need either a Linux build or a 32-bit Windows build.
