### ISSUE TITLE
Edgelines do not render correctly against TEXMAP imagery

### ISSUE THREAD

**Issue by alex-taylor** [tcobbs/ldview#23]
Edgelines that pass through a texmap image and also edgelines which merely appear in front of texmap imagery appear faint, as highlighted here:

![Image8](https://user-images.githubusercontent.com/5150717/83547878-c4472e80-a4fa-11ea-9807-6310b3dbf151.png)

Disabling line antialiasing resolves the second problem, but not the first:

![Image9](https://user-images.githubusercontent.com/5150717/83547971-eb9dfb80-a4fa-11ea-9f68-ea349c22a6cc.png)

**Comment by tcobbs** [comment]
This should now be fixed.
