### ISSUE TITLE
BFC with face highlighting is very slow

### ISSUE THREAD

**Issue by alex-taylor** [tcobbs/ldview#27]
This didn't used to be the case, although I'm not sure which was the last release that didn't have the issue.

If any form of face highlighting is enabled, rendering speed drops dramatically for all but the simplest models/parts.  It also drops off as you zoom into the model.

Interestingly, disabling BFC entirely runs much much faster.

**Comment by tcobbs** [comment]
BFC face highlighting is really only designed to be used when authoring parts. I cannot reproduce the issue. I strongly suspect that you either have an updated graphics driver or an updated graphics card, and that driver or card does not like the functionality I use for the face highlighting. LDView's rendering uses extremely old OpenGL functionality, and unfortunately I doubt that graphics card makers spend any time optimizing for it. Note that it's not surprising that highlighting faces is slower than completely disabling BFC.
