### ISSUE TITLE
Compilation failure on Ubuntu Gnome 16.10 64Bit

### ISSUE THREAD

**Issue by nathaneltitane** [tcobbs/ldview#3]
Currently trying to build from Git source and get these errors:

ldview (osmesa)

-------------------------------------
                                      ^
cd .obj-osmesa; g++    -o ../Headerize Headerize.o -L../../TCFoundation -L../../TRE -L../../LDLoader -L../../LDLib -L../../LDExporter -L/usr/X11R6/lib -L../TCFoundation -lTCFoundation-osmesa -ljpeg -lpng -lz
./Headerize ../Textures/StudLogo.png
./Headerize ../LDViewMessages.ini
g++ -o .obj-osmesa/ldview.o  -Wall -D_GNU_SOURCE -O3 -D_OSMESA -D_NO_BOOST -I.. -I../include  -c ldview.cpp
ldview.cpp:16:23: fatal error: GL/osmesa.h: No such file or directory
 #include <GL/osmesa.h>
                       ^
compilation terminated.

-------------------------------------

ldview (qt)

g++ -m64  -Wl,-O1 -o LDView .obj/QTMain.o .obj/ModelViewerWidget.o .obj/Preferences.o .obj/LDViewErrors.o .obj/LDViewExtraDir.o .obj/AlertHandler.o .obj/LDViewSnapshotSettings.o .obj/LDViewPartList.o .obj/misc.o .obj/LDViewJpegOptions.o .obj/LDViewModelTree.o .obj/LDViewBoundingBox.o .obj/LDViewMainWindow.o .obj/LDViewLatitudeLongitude.o .obj/LDViewMpdModel.o .obj/LDViewExportOption.o .obj/LDViewCustomizeToolbar.o .obj/moc_ModelViewerWidget.o .obj/moc_Preferences.o .obj/moc_LDViewErrors.o .obj/moc_LDViewExtraDir.o .obj/moc_LDViewPartList.o .obj/moc_LDViewJpegOptions.o .obj/moc_LDViewSnapshotSettings.o .obj/moc_LDViewModelTree.o .obj/moc_LDViewLatitudeLongitude.o .obj/moc_LDViewMpdModel.o .obj/moc_LDViewExportOption.o .obj/moc_LDViewMainWindow.o .obj/moc_About.o .obj/moc_LDViewCustomizeToolbar.o .obj/qrc_resources.o    -L/usr/X11R6/lib64 -L/usr/lib/x86_64-linux-gnu -L../TCFoundation -L../LDLib -L../LDLoader -L../TRE -L../boost/lib -lLDraw -L../LDExporter -lLDLoader -lTRE -lTCFoundation -lz -ljpeg -lpng -lGLU -lgl2ps -lLDExporter -ltinyxml -L../lib -l3ds-64 -lboost_thread -lboost_system -lpthread -lGL -lQtOpenGL -lQtGui -lQtCore 
/usr/bin/ld: cannot find -lboost_thread
/usr/bin/ld: cannot find -lboost_system
collect2: error: ld returned 1 exit status
Makefile:163: recipe for target 'LDView' failed
make: *** [LDView] Error 1

Libraries are seemingly installed and present on the system before build.

**Comment by tcobbs** [comment]
It looks like you don't have USE_CPP11 defined, which is causing the boost problems. At a guess, you don't have the OSMesa developer package installed, which is causing the OSMesa failure. You should define USE_CPP11 there as well, although I thought it was defined by default, and you had to go out of your way to have it not defined.

**Comment by pbartfai** [comment]
To fix OSMesa issue please install package libosmesa6-dev.

Recommended method is building debian package with script makdeb inside QT folder.

To compile Qt based binaries please use the following commands:

```
qmake -spec linux-g++-64 DEFINES+=USE_CPP11                        #  (on 64 bit linux)
qmake -spec linux-g++-32 DEFINES+=USE_CPP11                        #  (on 32 bit linux)
make
```
Or download package from [https://build.opensuse.org/package/show/home:pbartfai/LDView](url)

**Comment by nathaneltitane** [comment]
Resolved - thanks for the input.


Nathanel Titane,

*TND*esigns | Industrial + Graphic Design Solutions

Resume <https://www.dropbox.com/s/kbceyu8x5dspv3v/resume-en.pdf> | About
<http://nathaneltitane.com/about> | Portfolio <http://nathaneltitane.com> |
Blog <http://legolinux.com/> | Linkedin
<http://www.linkedin.com/in/nathaneltitane>

514 . 583 . 7386
