### ISSUE TITLE
Seg fault when using the command line to export files on Ubuntu 18.04

### ISSUE THREAD

**Issue by skoroneos** [tcobbs/ldview#31]
Greetings
Tried to use the command line to export some pov files and i am getting a seg fault on ubuntu 18.04
LDVIew is build from source without any errors and works fine when i enter the GUI to export the files

I run GDB and here is what i get

gdb --args /usr/bin/LDView 3010.ldr -ExportFile=3010.pov
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/LDView...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/LDView 3010.ldr -ExportFile=3010.pov
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe92d4700 (LWP 4555)]
[New Thread 0x7fffe8ad3700 (LWP 4556)]
[New Thread 0x7fffe3fff700 (LWP 4557)]
[New Thread 0x7fffe37fe700 (LWP 4558)]

Thread 1 "LDView" received signal SIGSEGV, Segmentation fault.
tcache_get (tc_idx=3) at malloc.c:2943
2943	malloc.c: No such file or directory.
(gdb) 

could it be similar to #14 ?

**Comment by skoroneos** [comment]
Forgot to mention version is 4.4 cloned from here

**Comment by tcobbs** [comment]
I strongly suspect this is due to the Qt changes that generally broke snapshot saving. You should be able to perform POV exports using the command line-only OSMesa version of LDView. So, while it is possible that we'll be able to fix this, using the OSMesa version is probably advisable as a workaround.

**Comment by skoroneos** [comment]
Thanks for the quick reply and all the effort you put into this. 
Yes the OSMesa works without a problem. Have seen other references in the GitHub issues and tried it out.
One thing that still haven't figured out is how to use the existing LDView config on the OSMesa version.
i.e -IniFile= /home/stelios/.config/LDView/LDView.conf does not work and the example on the instructions is not clear on how to add POV ray exporter specific configs

**Comment by pbartfai** [comment]
Tested latest source code on Ubuntu 18.04 build with Qt4.8.7 and and command line xport works file. 

@skoroneos please check and confirm.
