### ISSUE TITLE
Converting dat file hangs after 40 minutes

### ISSUE THREAD

**Issue by knobel-dk** [tcobbs/ldview#38]
Hi there.

Thanks for making this repo available!

I am trying to run LDView on Ubuntu 16.04 (below in Docker to show that it is a clean install of Ubuntu):

```
docker run -it --rm ubuntu:16.04 /bin/bash
apt update -yqq && apt install -yqq curl unzip apt-utils desktop-file-utils xvfb locales
locale-gen en_US.UTF-8
curl http://downloads.sourceforge.net/ldview/ldview-4.2-ubuntu-16.04.amd64.deb?download -L -o ldview-4.2-ubuntu-16.04.amd64.deb
dpkg -i ldview-4.2-ubuntu-16.04.amd64.deb
apt-get install -f
xvfb-run -e error.log -a LDView ldraw/parts/73436.dat -ExportFile=MyModel.pov
```

The last command prints and hangs with this message: `Failed to load translation en`

Any ideas on how to mitigate this? How long should converting a part simple part from Ldraw take? I'm running with 61 GB RAM and 1 Nvidia K80 GPU.

Thanks!

**Comment by tcobbs** [comment]
Exporting should be very fast for a single part. @pbartfai could this be caused by the translation load failing?

**Comment by pbartfai** [comment]
I have compiled the latest source code on Ubuntu 16.04 and it works. It exports in less than 2 seconds.

Please use  (`docker build -t ldview-test . ; docker run -it --rm ldview-test`) the following Dockerfile (I have commented out the lines which installed the old binary file):
```
FROM ubuntu:16.04

RUN apt update -yqq && apt install -yqq curl unzip apt-utils desktop-file-utils xvfb locales
RUN locale-gen en_US.UTF-8
#RUN curl http://downloads.sourceforge.net/ldview/ldview-4.2-ubuntu-16.04.amd64.deb?download -L -o ldview-4.2-ubuntu-16.04.amd64.deb
#RUN dpkg -i ldview-4.2-ubuntu-16.04.amd64.deb || true
#RUN apt-get install -f -y
RUN curl http://www.ldraw.org/library/updates/complete.zip -o complete.zip
RUN unzip -q complete.zip
RUN mv ldraw /usr/share
RUN rm -f complete.zip
RUN apt install -yqq git
RUN git clone https://github.com/tcobbs/ldview
RUN ./ldview/QT/docker/install-devel-packages.sh
RUN cd ldview/QT ; qmake -spec linux-g++-64 ; make
CMD cd ldview/QT ; xvfb-run -e error.log -a ./LDView /usr/share/ldraw/parts/73436.dat -ExportFile=MyModel.pov ; cat MyModel.pov
```

**Comment by knobel-dk** [comment]
Thanks, works great!
