### ISSUE TITLE
Use standard gtk dialog for open/save

### ISSUE THREAD

**Issue by nathaneltitane** [tcobbs/ldview#4]
The current LDView release does not use standard gtk open/save dialog. Being able to access shortcuts and recently used files/folders would greatly improve the overall user experience if implemented.

Other Qt-based applications, such as LeoCAD have implemented the use of that dialog.

Could it possibly be done?

Current Dialog:

![screenshot from 2017-10-24 14-46-41](https://user-images.githubusercontent.com/5674757/31961908-2b3d3366-b8ca-11e7-919e-3438575e865d.png)

What it should be:
![screenshot from 2017-10-24 14-47-45](https://user-images.githubusercontent.com/5674757/31961985-5043afe6-b8ca-11e7-98d3-1f938c990d3b.png)

Thank you

**Comment by pbartfai** [comment]
We use non-static functions of QFileDialog and only static functions use native file dialog. 

The disadvantage of static functions with native dialog is that the open/save (QFileDialog::Accept) button cannot be renamed to Export or to anything else.

**Comment by pbartfai** [comment]
Do you use Qt4.x version of LDView? Please test with Qt5.x version. I got native GTK file dialog with Qt5.x version.

**Comment by pbartfai** [comment]
file open is migrated to static function so it must be GTK native dialog on Qt4.x. Please note save snapshot is still not migrated.

**Comment by nathaneltitane** [comment]
Hi Peter,

I believe I am still building with qt4 at this very moment.
Does that mean it's only available with qt5?

**Comment by pbartfai** [comment]
Please rebuild latest source code against Qt4.x. It should be fixed.

**Comment by nathaneltitane** [comment]
Done. thanks


Nathanel Titane,

*Industrial Designer* | Industrial + Graphic Design Solutions

Resume <https://www.dropbox.com/s/y2vlokz70rw4gu8/graphic-resume.pdf> |
About <http://nathaneltitane.com/about> | Portfolio
<http://nathaneltitane.com> | Blog <http://legolinux.com/> | Linkedin
<http://www.linkedin.com/in/nathaneltitane>

514 . 583 . 7386
