### ISSUE TITLE
OSMesa version not working on Debian Buster

### ISSUE THREAD

**Issue by hubnedav** [tcobbs/ldview#40]
Hi, 

I'm trying to run OSMesa version on Debian Buster (both self compiled and installed form deb package, 4.3 and 4.4) and I keep getting following error message. 

```
OSMesa not working!
viewport: 0, 0, 0, 0
``` 

Everything works as espected when I try to run ldview on Debian Stretch, Ubuntu 21.04 or Alpine. 

Any ideas where the problem might be? Corrupted libosmesa on Debian Buster?  (I am trying with `debian:buster-slim`)

**Comment by pbartfai** [comment]
We alrady have experienced the same issue with standard OSMesa packages. Please try and rebuild OSMesa package from source and test LDView against it.

**Comment by pbartfai** [comment]
Recompiled mesa3d from source and problem is fixed. I used the following commands:

```apt-get build-dep mesa
wget https://archive.mesa3d.org/mesa-18.3.6.tar.xz
tar Jxf mesa-18.3.6.tar.xz
cd mesa-18.3.6
mkdir builddir
meson builddir
ninja -C builddir
sudo ninja -C builddir/ install
export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu
```
