### ISSUE TITLE
Camera jiggle in walk mode

### ISSUE THREAD

**Issue by mjhorvath** [tcobbs/ldview#44]
There is a slight jiggle after rotating the camera in walk mode. It is kind of annoying. I think it would be better if camera rotation used azimuth and altitude in walk mode like in a first-person shooter video game, thereby eliminating the jiggle. Thanks!

**Comment by tcobbs** [comment]
I don't understand what you mean. Having said that, I don't think I can fix whatever it is. LDView isn't a game, and (more pertinent) I'm not a game developer. I don't like how walk and fly mode work in LDView, but I don't really have the knowledge to fix them.

**Comment by mjhorvath** [comment]
The "jiggle" happens after you rotate the camera. The camera snaps back into a certain orientation. If the camera worked correctly in the first place, it would not have to snap back into position afterward.

I took a look at the code and couldn't figure it out how to fix it, either. I just thought I'd list the issue here.

**Comment by tcobbs** [comment]
What I meant is that I don't have the knowledge to fix the problem. As an aside, I don't even see the problem (although I didn't test at super low frame rates).
