### ISSUE TITLE
LDView.com error from command line

### ISSUE THREAD

**Issue by mjhorvath** [tcobbs/ldview#52]
When I try to run the program from the command line like this:

`"C:\Program Files (x86)\LDraw\LDView\LDView.com" a0902.dat`

I get the error:

"Error loading model D:\GitHub\LDBoxer\boxes\parts\b\Files."

I think the program is detecting the "Files" string in "Program Files (x86)". Not sure.

**Comment by tcobbs** [comment]
@mjhorvath I'm pretty sure I fixed this. Send an email to the LDView email address, and I'll send you a test build.
