### ISSUE TITLE
CommandLinesList not working properly

### ISSUE THREAD

**Issue by LeoKonzett** [tcobbs/ldview#54]
Hello Mr Cobbs,

I was recently trying out the -CommandLinesList flag in LDView 4.4 
The .txt file I used was as follows:
"
Common: -ExportFiles=1 -ExportSuffix=.pov
C:\Users\d92358\PycharmProjects\similarity-learner-lego\lego_parts\4035\4035_110_3.ldr -DefaultLatLong=62,-148 -DefaultZoom=0.669948702925056
C:\Users\d92358\PycharmProjects\similarity-learner-lego\lego_parts\4035\4035_128_1.ldr -DefaultLatLong=41,-6 -DefaultZoom=0.6372951562579559
C:\Users\d92358\PycharmProjects\similarity-learner-lego\lego_parts\4035\4035_14_4.ldr -DefaultLatLong=26,104 -DefaultZoom=0.6580539536189575
C:\Users\d92358\PycharmProjects\similarity-learner-lego\lego_parts\4035\4035_17_2.ldr -DefaultLatLong=34,110 -DefaultZoom=0.7329548691690021
C:\Users\d92358\PycharmProjects\similarity-learner-lego\lego_parts\4035\4035_70_0.ldr -DefaultLatLong=39,160 -DefaultZoom=0.8441890217408936
"

However, while all five .ldr files get exported to .pov file format, the DefaultLatLong option does not work. This means that all five rendered images are displayed with the same viewing angle as opposed to the different angles I have indicated in the .txt file. How could this be caused?

Many thanks in advance

**Comment by LeoKonzett** [comment]
Just to further clarify:
Previously I used the variant without the -CommandLinesList flag and it worked fine. I implemented the relevant code in Python but am pretty sure that there are no errors in it.

**Comment by tcobbs** [comment]
@LeoKonzett: Sorry for the delay. I think I have this fixed. If you send me an email at LDView's email address, I can send you a test build (as long as you use Windows or macOS). Let me know which OS, and if you use Windows, let me know if your Windows is 64 bit.

**Comment by tcobbs** [comment]
Since I didn't receive any feedback, I am assuming that my fix worked.
