### ISSUE TITLE
AA not functioning

### ISSUE THREAD

**Issue by nathaneltitane** [tcobbs/ldview#6]
[ldview_gl_info.txt](https://github.com/tcobbs/ldview/files/1545941/ldview_gl_info.txt)
AA settings have no effect when toggled.

I've attached a comparison shot in between leocad (with functioning AA) and LDView (with AA setting enabled but not functioning).

I've also attached the gl_info for my current setup.

Thanks

![screenshot from 2017-12-10 13-44-06](https://user-images.githubusercontent.com/5674757/33808223-b8c95682-ddb0-11e7-98d8-6b8c7e6143cd.png)

**Comment by pbartfai** [comment]
@nathaneltitane please check the problem again. It works for me on Fedora 35 using latest source code.

**Comment by nathaneltitane** [comment]
will test when I get my NUC
