### ISSUE TITLE
Material properties seem to be applied to non-colour-16 parts in a type-1 line

### ISSUE THREAD

**Issue by alex-taylor** [tcobbs/ldview#63]
Title's probably not too clear, sorry.  I've tested with LDView 4.4.1 on Win64.

The issue can be seen if you load the following code:

0 FILE main.ldr
1 60 0 0 0 1 0 0 0 1 0 0 0 1 subModel-1.ldr
0 FILE subModel-1.ldr
1 0 0 0 0 1 0 0 0 1 0 0 0 1 22969a.dat

LDView should be configured with specular highlighting enabled.

The submodel contains a single part in black.  The main model contains a reference to the submodel with a metallic colour selected.  Obviously this should have no effect, since there are no colour-16 parts in the submodel.  But while the colour of the submodel is unaffected, the material properties of the metallic colour are apparently applied to the render, and it displays with metallic specular highlighting...

![sample1](https://user-images.githubusercontent.com/5150717/170841281-965dc271-a7bb-4950-b6cc-00c1eb00960d.png)

**Comment by tcobbs** [comment]
Thanks for the report.  I tracked down the source of the problem and committed a fix: https://github.com/tcobbs/ldview/commit/c134e40a6d9ebb392d9b3fe3d4e2984cbc9e201c

This fix will be in the next release.
