### ISSUE TITLE
No antialias

### ISSUE THREAD

**Issue by perjahn** [tcobbs/ldview#76]
**Describe the bug**
Lines/edges has no antialias.

**To Reproduce**
Load car model, enable Antialiased lines in Preferences, inspect pixels of any edge.

**Expected behavior**
Lines/edges should have antialias.

**Platform (please complete the following information):**
 - OS: Kubuntu Linux
 - Version: 23.04
 - CPU Architecture: X86-64
 - GPU: Geforce 3090. Drivers 470.199.02

**Additional context**
LeoCad has antialias of edges/lines.

**Comment by pbartfai** [comment]
I could test only on Fedora 38 with Mesa3d. Antialias works well.
With antialias enabled:
![image](https://github.com/tcobbs/ldview/assets/7771817/9e0243d1-d2b0-4fb6-9594-ee1cc96f40ee)
Without antialias:
![image](https://github.com/tcobbs/ldview/assets/7771817/41b50846-bcfe-4d2f-8ee6-af18d81203ed)
Which version of LDView do you use?

**Comment by perjahn** [comment]
I'm runnning LDView 4.5 (Apr 23 2023)

**Comment by pbartfai** [comment]
Which package do you use? 
Do you use binary package or built from source code? 
Which version of Qt?

**Comment by perjahn** [comment]
ldview-qt5-4.5-ubuntu-22.04.amd64.deb
from: https://github.com/tcobbs/ldview/releases/download/v4.5/ldview-qt5-4.5-ubuntu-22.04.amd64.deb

I've also tried the LDView_4.5.dmg, on a m2 mbp, with "Antialiased lines", and got no antialias there as well.
![image](https://github.com/tcobbs/ldview/assets/2880776/e20832f9-0309-465e-b166-76f19f3c2b7b)

**Comment by tcobbs** [comment]
> ldview-qt5-4.5-ubuntu-22.04.amd64.deb from: https://github.com/tcobbs/ldview/releases/download/v4.5/ldview-qt5-4.5-ubuntu-22.04.amd64.deb
> 
> I've also tried the LDView_4.5.dmg, on a m2 mbp, with "Antialiased lines", and got no antialias there as well. ![image](https://user-images.githubusercontent.com/2880776/257916578-e20832f9-0309-465e-b166-76f19f3c2b7b.png)

Your screenshot does not contain any lines or edge lines. The "Antialias lines" setting only works on lines and edge lines, not polygon face edges. LDView only supports fullscreen antialiasing in Windows. If you enable Edge Lines, you should see the antialiasing.

**Comment by perjahn** [comment]
Solved it, thank you!
