### ISSUE TITLE
scale option not available in export STL on linux

### ISSUE THREAD

**Issue by jasonblewis** [tcobbs/ldview#79]
**Describe the bug**
the scale option for STL export is not available to select on linux

**To Reproduce**
download linux version, 
load .dat file
File/Export
Select STL
note there is no way to set scale (see screenshot)

**Expected behavior**
there should be a way to select the export scale (as there is in the windows build

**Screenshots**
![Screenshot from 2023-12-15 14-44-14](https://github.com/tcobbs/ldview/assets/129165/a591f9d7-f0bd-4cee-90ad-002bbaf88f92)

**Platform (please complete the following information):**
 - OS: [ Linux] Debian 12 under wayland
 - 
 - CPU Architecture: X86-64

**Additional context**

**Comment by pbartfai** [comment]
@tcobbs Added the Qt code for STL Export Options under the File menu similar to POV/3DS, but the settings list is empty. Please check the backend.

**Comment by tcobbs-bentley** [comment]
@pbartfai I suspect that your existing Qt code does not support the single ungrouped setting that is present for STL. Both POV and 3DS settings are all grouped. If you debug your `populate`, you should find that the `LDExporterSettingList` has one and only one entry, and that entry is of type `TEnum`. Here's what I see in macOS:

<img width="386" alt="Screenshot 2023-12-15 at 9 21 53 AM" src="https://github.com/tcobbs/ldview/assets/77415528/5a1330db-059d-42bb-80fb-5f2ca22ce71b">

Let me know if you see something different in your `settings` list.

**Comment by pbartfai** [comment]
Fixed. Please download latest binaries from OBS https://build.opensuse.org/projects/home:pbartfai/packages/LDView-qt5/repositories/Debian_12/binaries

**Comment by jasonblewis** [comment]
thank you. i am now able to set the pref before exporting.
