### ISSUE TITLE
Chaining SaveSnapshot with other preferences like DefaultLatitude 

### ISSUE THREAD

**Issue by benediktbosshammer** [tcobbs/ldview#8]
I'm trying to take a series of snapshots of a model with different angles from the command line and tried to use the following command:
`./LDView 3002.dat -DefaultLatitude=10 -DefaultLongitude=10 -SaveSnapshot=test.png`

`./LDView 3002.dat -DefaultLatitude=10 -DefaultLongitude=10` works fine but not with -SaveSnapshot..

Is this the preferred way of usage or is there a different way to achieve a series of snapshots from different angles using the command line?

OS: MacOS

**Comment by tcobbs** [comment]
That's supposed to work, and I can't think of a reason off-hand why it
wouldn't. (I'll investigate.) Having said that, there is an alternative
that should work: -cg. (See the "L3P-compatible Options" section of
LDView's Help.html.) The following is an example for 30 degrees latitude
and 45 degrees longitude:

./LDView 3002.dat -cg30,45 -SaveSnapshot=test.png

This also optionally lets you specify a radius (distance from camera to
center of model). So if you want to take multiple snapshots from different
angles that all have the same zoom level, you would use that, like:

./LDView 3002.dat -cg30,45,50000 -SaveSnapshot=test.png

In that case it's up to you to calculate an appropriate radius for your
model's size and the FOV setting you use for LDView.

--Travis

**Comment by tcobbs** [comment]
I did some digging, and -DefaultLatitude and -DefaultLongitude aren't meant
to be used on the command line. They configure the default values to use
when the LDView UI is in latitude/longitude rotation mode. There is no way
on the command line to switch to that mode, and command line snapshots may
not pay attention to that setting even if the UI is in that mode. In
addition to the -cg option I already mentioned, you can also use
-DefaultLatLong=<lat>,<long>. However, that option does not support the
optional radius parameter that -cg supports.

--Travis

**Comment by benediktbosshammer** [comment]
Thanks for your fast reply. Thats exactly what we are looking for! Really appreciate your help! Keep up the great work!!
