### ISSUE TITLE
Save dialogs don't work properly on GNOME

### ISSUE THREAD

**Issue by zoqaeski** [tcobbs/ldview#9]
The dialogs that are summoned when exporting or saving don't allow you to enter a filename; you can only select existing files in the folder and overwrite them. If there are no files of the required filetype, the Save/Export button remains greyed out.

![screenshot from 2018-07-07 14-04-39](https://user-images.githubusercontent.com/172912/42406631-e689aa6c-81ee-11e8-8916-967078f93b1a.png)

Operating system is Arch Linux x86-64, desktop is GNOME 3.28.2, LDView is 4.3.

**Comment by pbartfai** [comment]
I have tested latest source code on both Qt4.x & 5.x and problem not experienced. Could you please  install latest package from OBS: 
https://build.opensuse.org/package/show/home:pbartfai/LDView or
https://build.opensuse.org/package/show/home:pbartfai/LDView-qt5

**Comment by pbartfai** [comment]
@zoqaeski is the problem still present? Have you tested with latest binaries?

**Comment by pbartfai** [comment]
Tested with latest ArchLinux using Qt5.x version of LDView and it works well.
